#!/bin/bash
go run ./main.go https://google.com \
https://youtube.com \
https://tmall.com \
https://facebook.com \
https://baidu.com \
https://qq.com \
https://sohu.com \
https://taobao.com \
https://login.tmall.com \
https://wikipedia.org \
https://yahoo.com \
https://amazon.com \
https://jd.com \
https://360.cn \
https://weibo.com \
https://sina.com.cn \
https://pages.tmall.com \
https://reddit.com \
https://live.com \
https://vk.com \
https://okezone.com \
https://netflix.com \
https://blogspot.com \
https://csdn.net \
https://alipay.com \
https://instagram.com \
https://office.com \
https://aliexpress.com \
https://xinhuanet.com \
https://yahoo.co.jp \
https://bing.com \
https://microsoft.com \
https://twitter.com \
https://google.com.hk \
https://stackoverflow.com \
https://livejasmin.com \
https://ebay.com \
https://naver.com \
https://babytree.com \
https://amazon.co.jp \
https://twitch.tv \
https://tribunnews.com \
https://google.co.in \
https://apple.com \
https://pornhub.com \
https://tianya.cn \
https://msn.com \
https://microsoftonline.com \
https://yandex.ru \
https://myshopify.com  >> result.out