// Code generated by "stringer -type=Mode"; DO NOT EDIT.

package conv

import "strconv"

const _Mode_name = "TemperatureDistanceWeight"

var _Mode_index = [...]uint8{0, 11, 19, 25}

func (i Mode) String() string {
	i -= 1
	if i < 0 || i >= Mode(len(_Mode_index)-1) {
		return "Mode(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Mode_name[_Mode_index[i]:_Mode_index[i+1]]
}
